---
# note: current_user is a dependency, but it won't run
# if you use a tag to select just the daemon tasks
- include_role:
    name: marvel-nccr.current_user
  when: current_user is undefined

- name: Add AiiDA Daemon as system service
  become: true
  become_user: "{{ root_user }}"
  template:
    src: aiida-daemon@.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  vars:
    daemon_user: "{{ current_user }}"
    daemon_user_home: "{{ current_user_home }}"
    daemon_aiida_venv: "{{ aiida_venv |  regex_replace('\\$\\{ansible_env.HOME}', current_user_home) }}"

- name: Start AiiDA Daemon system service
  become: true
  become_user: "{{ root_user }}"
  systemd:
    name: aiida-daemon@{{ aiida_profile_name }}
    enabled: true
    masked: false
    daemon-reload: true
    state: restarted
  when: not (cloud_platform is defined and cloud_platform == 'docker')
