---
- name: "install aiida-siesta-{{ aiida_siesta_version }} from PyPI"
  pip:
    name: aiida-siesta
    version: "{{ aiida_siesta_version }}"
    virtualenv: "{{ aiida_venv }}"
  register: pip_install

- name: run reentry scan
  shell: "{{ aiida_venv }}/bin/reentry scan -r aiida"
  when: pip_install.changed


- name: set up siesta codes for localhost
  include_tasks: code-setup.yml
  vars:
   - aiida_code:
       name:  "siesta-{{siesta_version}}"
       template:  siesta.code
       executable: "{{ item }}"
       folder: "{{ siesta_topdir }}/Obj"
   - aiida_computer_name:  "{{ aiida_localhost_name }}"
  with_items: "{{siesta_executables}}"
  when: siesta_executables is defined

- include_role:
    name: release_notes
  vars:
    section: AiiDA
    option: aiida-siesta
    value: >-
      aiida-siesta {{ aiida_siesta_version }} is installed.
  when: release_notes is defined and release_notes
