---
- name: "install aiida-cp2k-{{ aiida_cp2k_version }} from PyPI"
  pip:
    name: aiida-cp2k
    version: "{{ aiida_cp2k_version }}"
    virtualenv: "{{ aiida_venv }}"
  register: pip_install

- name: run reentry scan
  shell: "{{ aiida_venv }}/bin/reentry scan -r aiida"
  when: pip_install.changed

- name: set up cp2k codes for localhost
  include_tasks: code-setup.yml
  vars:
   - aiida_code:
       name:  "cp2k-{{cp2k_version}}"
       template:  cp2k.code
       executable: "{{ item }}"
       folder: "{{ cp2k_topdir }}/exe"
   - aiida_computer_name:  "{{ aiida_localhost_name }}"
  with_items: "{{cp2k_executables}}"
  when: cp2k_executables is defined

- include_role:
    name: release_notes
  vars:
    section: AiiDA
    option: aiida-cp2k
    value: >-
      aiida-cp2k {{ aiida_cp2k_version }} is installed.
  when: release_notes is defined and release_notes
