---
- include_role:
    name: marvel-nccr.current-user
  when: current_user is undefined

- name: Add AiiDA REST API system service template
  become: true
  become_user: "{{ root_user }}"
  template:
    src: aiida-rest.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  vars:
    daemon_user: "{{ current_user }}"
    daemon_user_home: "{{ current_user_home }}"
    daemon_aiida_venv: "{{ aiida_venv |  regex_replace('\\$\\{HOME}', current_user_home) }}"

- name: Start AiiDA REST API system service
  become: true
  become_user: "{{ root_user }}"
  systemd:
    name: aiida-rest
    enabled: "{{ aiida_rest_service_enabled }}"
    masked: false
    daemon-reload: true
  when: not (cloud_platform is defined and cloud_platform == 'docker')
