---
- name: Converge
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: marvel-nccr.aiida
      vars:
        aiida_components:
          - computers
          - plugins
          - pseudopotentials
          - examples
        # just to test whether this also works
        aiida_data_folder: "/usr/local/share"
